version: '3'

services:
  database:
    container_name: 'postgres'
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    restart: on-failure
  
  php-api:
    container_name: 'php-api'
    build:
      context: .
      dockerfile: dockerfile.php
    depends_on:
      database:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - .:/lamoda_tech

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "${NGINX_PORT:-80}:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/lamoda_tech/
    depends_on:
      - php-api
